# configs/config.yml
data_path: "data/raw/building_permits.csv"
processed_data_path: "data/processed/permisos_limpios.csv"

cols_to_drop:
  - "Street Number Suffix"
  - "Unit Suffix"
  - "Site Permit"

date_cols:
  - "Permit Creation Date"
  - "Current Status Date"
  - "Issued Date"
  - "Filed Date"

null_handling_config:
  drop_rows_if_null:
    - "Record ID"
  impute_as_category:
    "Completed Date": "Ongoing"
    "Expiration Date": "Does Not Expire"
  impute_with_median:
    - "Estimated Cost"
    - "Revised Cost"
    - "Existing Units"
    - "Proposed Units"
  impute_with_mode:
    - "Permit Type Definition"
    - "Street Suffix"
    - "Existing Construction Type Description"
    - "Proposed Construction Type Description"
    - "Supervisor District"
    - "Zipcode"